# Jykell configuration
# highlighter: pygments
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
  auto_ids: true
  input: GFM
  toc_levels: 1..3

highlighter: none
paginate: 15
language: 'en-uk'
host_url: 'https://art-collection.cc'

# Website info
name: '艺术工作室'
description: "Yu's art collection"

# Author's info
author: 'Xu Jiayu'
# edit 'categories' in the front matter of every post to match this username
nickname: Yu
bio: 'Arts / Painting / Music drama'
location: 'Guangxi, China'
url: ''
img_url: ''
image: 'assets/images/cover3.jpg'

short_url: 'art-collection.cc'
google_analytics: 
disqus: 
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: 

# Permalinks
# permalink: /:title
permalink: pretty
# permalink: /tag/:tag

# gems and other configs
plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-toc
whitelist:
  - jekyll-redirect-from

exclude: [vendor]

sass:
  style: compressed

safe: false
lsi: false
username: ms
repo: jekyll-blog
branch: master
# relative_source: ../jasper/
# destination: ../jasper-pages/
production_url:  https://biomadeira.github.io/jasper/
source_url:      https://github.com/biomadeira/jasper/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
